### ISSUE TITLE
Request to merge this project into bash-completion.

### ISSUE THREAD

**Issue by 99-lives** [imomaliev/tmux-bash-completion#4] opened 2017-01-09 00:13 UTC
This project requires [bash-completion](https://github.com/scop/bash-completion) to function, and it places its files in the same location as `bash-completion`. It should be very easy to merge the code in this project into `bash-completion`. This would mean that users do not have to install a separate package to use bash completion for tmux, as it would be available in the `bash-completion` package, which is pre-installed on many Linux distributions.

If there is some reason that this project should remain separate, please enlighten me, but I think that it would be better for users to only need to install `bash-completion`, the de facto standard for bash completion on Linux.

**Comment by imomaliev** [comment] 2017-01-11 05:42
Hello this duplicate of https://github.com/imomaliev/tmux-bash-completion/issues/1, also please read this https://github.com/scop/bash-completion/pull/81

**Closed as completed by imomaliev** 2017-01-11 05:42 UTC
